version: '3'

volumes:
  db:

services:
  volumes-provisioner:
    image: hasnat/volumes-provisioner
    environment:
      PROVISION_DIRECTORIES: "1001:0:0766:/db"
    volumes:
      - "./db:/db:rw"
  redis:
    image: "redislabs/redisearch:latest"
    ports:
      - "6379:6379"
  datastore:
    image: "maguec/fortune500-search"
    links:
      - "redis:redis"
    ports:
      - "5000:5000"
    environment:
        - REDIS_SERVER=redis
        - REDIS_PORT=6379
  insight:
    image: "redislabs/redisinsight:latest"
    volumes:
      - "./db:/db:rw"
    ports:
      - "8001:8001"
